resources:
- base.yml
# - service-account.yml

namespace: spinnaker

patchesStrategicMerge:
- delete-expose.yml
# - delete-files.yml
- patch-minio.yml
- patch-profiles-gate.yml
- patch-profiles-deck.yml
#- patch-profiles-echo.yml
- patch-profiles-clouddriver.yml
- patch-igor.yml
- patch-clouddriver-sa.yml
- patch-enable-features-artifacts.yml
- patch-enable-http-artifact.yml
- patch-provider-kubernetes.yml
- patch-armory-secrets-vault.yml
- patch-jenkins.yml
#- patch-gate-basicauth.yml
- patch-api-v1.yml
- patch-endpoint.yml
