apiVersion: v1
kind: ConfigMap
metadata:
  name: halyard-custom-config
data:
  halyard-local.yml: |
    secrets:
      vault:
        enabled: true
        url: https://spinnaker-vault.vault.svc.cluster.local:8200
        path: kubernetes
        role: spinnaker
        authMethod: KUBERNETES
